//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoonMembers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class members
    {
        public int memberId { get; set; }
        public string memberName { get; set; }
        public string memberEmail { get; set; }
        public string memberPhoto { get; set; }
        public System.DateTime memberBirthdate { get; set; }
        public int memberOrder { get; set; }
    }
}
